### ISSUE TITLE
Add a "usage"

### ISSUE THREAD

**Issue by ragnar76** [kallaballa/Poppy#3]
Hi there,

when you start Poppy without any options, you'll get this:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Abgebrochen (Speicherabzug geschrieben)
```
Would be nice to print something like this:
`Usage: poppy image-1.png image-2.png image-3.png`

**Comment by kallaballa** [comment]
fixed
